  "1BF050-7490EB-AE6BEB\n"    /* pass */ \
  "FC56B55198E28-6EDAC8\n"    /* fail */ \
  "20A97C-K78B2E-ECCD58\n"    /* fail */ \
  "\t17E6B0-93DC11-99EB8E\n"  /* fail */ \
  "  52AB14-5BD3A2-2C6F5E\n"  /* fail */ \
  "ADC68D-A6D0CB-A54CC\n"     /* fail */ \
  "141899-A504B5-31A714\t\n"  /* pass */ \
  "857CE0-21C51A-B209AD  \n"  /* pass */ \
  "52AB14C-9304F-69340D\n"    /* fail */ \
  "AAD452-1FE824-0B8EE4"      /* pass */ ;
