  "    \n"                                                   /* fail */ \
  "1EE79B-889A3A-2A40CD LXDE, comp\n"                        /* pass */ \
  "1EE79B-135B85-DE5620 someone's try to kill all humans\n"  /* pass */ \
  "\t\t\t\n"                                                 /* fail */ \
  "1EE79B-F314F1-22134C try to escape hyphen\\\n"            /* fail */ \
  "1EE79B-C71527-9BC445  winter,tree,  moon, rating:5   \n"  /* pass */ \
  "1EE79B-A8782C-E286F0 second \" try to escape \' hyphen\n" /* pass */ \
  "1EE79B-4171A7-2250BA solar system, planets\n"             /* pass */ \
  "1EE79B-35F304-DDC9DA she is watching you\n"               /* pass */ ;
