  "    \n"                                                   /* fail */ \
  "1EE79B-889A3A-2A40CD /home/user/.walls/lxde_green.jpg\n"  /* pass */ \
  "1EE79B-135B85-DE5620 \t/home/user/.walls/77156662.jpg\n"  /* pass */ \
  "\t\t\t\n"                                                 /* fail */ \
  " 1EE79B-F314F1-22134C ~/.walls/roz_5_1024.jpg\n"          /* fail */ \
  "1EE79B-C71527-9BC445 ~/.walls/1133-2.jpg   \n"            /* pass */ \
  "1EE79B-A8782C-E286F0 ~/.walls/amg_4t_1532.jpg\n"          /* pass */ \
  "1EE79B-4171A7-2250BA ~/.walls/01331 trajectory.jpg\n"     /* pass */ \
  "1EE79B-35F304-DDC9DA ~/.walls/ lain_rz_6591.jpg\n"        /* pass */ ;
