  "    \n"                                                   /* fail */ \
  "00000000A52DA178 /home/user/.walls/lxde_green.jpg\n"    /* pass */ \
  "00000000A52D4BB1 \t/home/user/.walls/77156662.jpg\n"    /* pass */ \
  "\t\t\t\n"                                                 /* fail */ \
  " 0000000078A7C574 ~/.walls/roz_5_1024.jpg\n"            /* fail */ \
  "0000000078A7DDE0 ~/.walls/1133-2.jpg   \n"              /* pass */ \
  "0000000078A7D5FB ~/.walls/amg_4t_1532.jpg\n"            /* pass */ \
  "0000000078A7C717 ~/.walls/01331 trajectory.jpg\n"       /* pass */ \
  "0000000078A7AB3C ~/.walls/ lain_rz_6591.jpg\n"          /* pass */ ;
