  "    \n"                                                   /* fail */ \
  "00000000A52DA178 LXDE, comp\n"                          /* pass */ \
  "00000000A52D4BB1 someone's try to kill all humans\n"    /* pass */ \
  "\t\t\t\n"                                                 /* fail */ \
  "0000000078A7C574 try to escape hyphen\\\n"              /* fail */ \
  "0000000078A7DDE0  winter,tree,  moon, rating:5   \n"    /* pass */ \
  "0000000078A7D5FB second \" try to escape \' hyphen\n"   /* pass */ \
  "0000000078A7C717 solar system, planets\n"               /* pass */ \
  "0000000078A7AB3C she is watching you\n"                 /* pass */ ;
