  "    \n"                                                   /* fail */ \
  "00000000-A52D-A178 LXDE, comp\n"                          /* pass */ \
  "00000000-A52D-4BB1 someone's try to kill all humans\n"    /* pass */ \
  "\t\t\t\n"                                                 /* fail */ \
  "00000000-78A7-C574 try to escape hyphen\\\n"              /* fail */ \
  "00000000-78A7-DDE0  winter,tree,  moon, rating:5   \n"    /* pass */ \
  "00000000-78A7-D5FB second \" try to escape \' hyphen\n"   /* pass */ \
  "00000000-78A7-C717 solar system, planets\n"               /* pass */ \
  "00000000-78A7-AB3C she is watching you\n"                 /* pass */ ;
