  "    \n"                                                   /* fail */ \
  "00000000-A52D-A178 /home/user/.walls/lxde_green.jpg\n"    /* pass */ \
  "00000000-A52D-4BB1 \t/home/user/.walls/77156662.jpg\n"    /* pass */ \
  "\t\t\t\n"                                                 /* fail */ \
  " 00000000-78A7-C574 ~/.walls/roz_5_1024.jpg\n"            /* fail */ \
  "00000000-78A7-DDE0 ~/.walls/1133-2.jpg   \n"              /* pass */ \
  "00000000-78A7-D5FB ~/.walls/amg_4t_1532.jpg\n"            /* pass */ \
  "00000000-78A7-C717 ~/.walls/01331 trajectory.jpg\n"       /* pass */ \
  "00000000-78A7-AB3C ~/.walls/ lain_rz_6591.jpg\n"          /* pass */ ;
